### ISSUE TITLE
General confusion

### ISSUE THREAD

**Issue by ghost** [sdeleuze/kowasm#33]
Sorry for bumping in and I have full forgiveness if this is deleted because wrong forum but I have a couple of inquiries I wondered if I could run with someone?
I'm aware that WebAssembly GC is all the rage and we are all anxiously awaiting stabler times - BUT - given that you could run Kotlin code [ages ago](https://medium.com/@mumarov/how-to-get-started-with-kotlin-native-and-web-assembly-baa2813f0d9) in the browser, why didn't more of the juice, sassy stuff wasm is promising us happened then? Or is Kotlin just generally interpreted as a JVM language?
Given that `konanc -target wasm32` is being deprecated, is this implying a "wasmNative" source set/build target at a later stage?
When I run `./bin/jsinterop` in my Kotlin distribution folder I get `Exception in thread "main" java.lang.IllegalArgumentException: Please choose either kotlinx.interop.wasm.math or kotlinx.interop.wasm.dom for -pkg argument` and more as an error message, is this implying I could get - somehow - use `./bin/cinterop` to output a wasm file? If not, why not? Also, why is WasmEdge and Wasmtime claiming they do not support Kotlin? Should I not be able to just run a konanc-wasm32 file in either WasmEdge, Wasmtime, Wasmer or KoWasm as hosts?

Thank you for any and all answers!

**Comment by a-cosmic-jaw** [comment]
Also if anyone could direct me to the kotlinx-interop repo? I sure can't find it using my normal channels!

**Comment by skuzmich** [comment]
Kotlin/Native (konan) wasm32 target was an experiment to adapt Kotlin's Native LLVM-based toolchain to produce Wasm. This approach turned out not future-proof with Wasm GC, and the Kotlin Team decided to work on a dedicated Kotlin/Wasm platform instead. Think about it as a Wasm-focused "fresh start", rather than a continuation of the Kotlin/Native wasm32 target.

> given that you could run Kotlin code [ages ago](https://medium.com/@mumarov/how-to-get-started-with-kotlin-native-and-web-assembly-baa2813f0d9) in the browser, why didn't more of the juice, sassy stuff wasm is promising us happened then? Or is Kotlin just generally interpreted as a JVM language?

Kotlin/Native wasm32 target development was suspended at some point to focus on Kotlin/Wasm.
Kotlin/Wasm is now released as Alpha and is in active development.
I'd be happy to comment on the status of "juice, sassy stuff".  What do you have in mind?

> Given that konanc -target wasm32 is being deprecated, is this implying a "wasmNative" source set/build target at a later stage?

I think the Gradle target was also named "wasm32", and is also now removed.

> When I run ./bin/jsinterop in my Kotlin distribution folder I get Exception in thread "main" java.lang.IllegalArgumentException: Please choose either kotlinx.interop.wasm.math or kotlinx.interop.wasm.dom for -pkg argument and more as an error message, is this implying I could get - somehow - use ./bin/cinterop to output a wasm file? If not, why not?

The new Kotlin/Wasm target does have cintreop, jsinterop and kotlinx.interop.
It has a new approach to JS interop https://kotlinlang.org/docs/wasm-js-interop.html, which is closer to Kotlin/JS.

> Also, why is WasmEdge and Wasmtime claiming they do not support Kotlin? 

These runtimes do not yet support Wasm GC, required for Kotlin/Wasm.

> Should I not be able to just run a konanc-wasm32 file in either WasmEdge, Wasmtime, Wasmer or KoWasm as hosts?

konanc-wasm32 is no longer supported. It was focused on running in browsers, but you could, in theory, implement runtime-specific replacements for the generated JS files.

**Comment by a-cosmic-jaw** [comment]
Thank you for a well formulated and quick response - with "juice, sassy stuff" I meant for example edge or cloud computing where WA is promising a whole lot of speed...
I'm pondering about writing a game engine in the spirit of Love2d and for this I have had four approaches - Load klib file, load wasm/wasi file, load dylib or load .kts file...
* Klib - I have yet to see an example of a dependency injection at runtime (even though I'm looking through the "jetbrains/kotlin" and "jetbrains/kotlin-native" GitHub repos as we speak... Pretty fun reads if I do say so myself :) Problem is that for example  `org.jetbrains.kotlin.konan.file .File` is java.io-based because apparently the native compiler runs in JVM? Oh, well...
* wasm/wasi - All solutions so far found is using GC and native memory-managed solutions just went deprecated a year ago :(
* .kts - Slow and wonky to get going with f.e. auto-complete in IntelliJ but does compilation and hot loading "well"
* dylib - the compiled .dylib file (compiled with `$ kotlinc-native -p dynamic test.kt`) is about 1MB large for a simple "Hello, world!" example (the .klib is 3.9KB and it takes way to long to compile...
To me it feels that JetBrains has taken the long route with this - all JS dependencies just adds a whole lot on top, f.ex. the repo `github.com/kotlin/kotlin-wasm-examples/browser-example` "kotlin-js-store/yarn.lock" loads 399 libraries...

**Comment by skuzmich** [comment]
Initially, Wasm 1.0 was released as an MVP for running C, a subset of C++, and similar languages. Kotlin has indeed taken a longer route, focusing efforts to target newer Wasm versions, where it could compete with platforms like JVM. Wasmtime is working on GC support at the moment, hopefully we'll see edge or cloud computing use cases covered soon.

> kotlin-js-store/yarn.lock" loads 399 libraries

These are "dev" dependencies, coming from webpack and friends, and they are not included in the final artifact. Kotlin/Wasm reused Kotlin/JS infrastructure for bundling, to get things going faster, but I agree that it is unnecessary for simple projects and should be made opt-in at some point.

**Comment by sdeleuze** [comment]
Thanks for providing feedback @skuzmich.
